In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv("C:\\Users\\janud\\Downloads\\Hr attrition dataset\\Data\\WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [72]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [74]:
df.shape

(1470, 35)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [78]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [80]:
# target value
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [82]:
df.drop(
    columns=[
        "EmployeeCount",
        "EmployeeNumber",
        "Over18",
        "StandardHours"
    ],
    inplace=True
)

In [84]:
# encode the target 
df["Attrition"] = df["Attrition"].map({
    "No":0,
    "Yes":1
})

In [86]:
df["Attrition"].value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

In [88]:
#binary column 
binary_cols = ["Gender", "OverTime"]

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in binary_cols:
    df[col] = le.fit_transform(df[col])

In [90]:
df[["Gender","OverTime"]].head()

   Gender  OverTime
0       0         1
1       1         0
2       1         1
3       0         1
4       1         0

In [92]:
#One-Hot Encode Remaining Columns
df = pd.get_dummies(
    df,
    columns=[
        "BusinessTravel",
        "Department",
        "EducationField",
        "JobRole",
        "MaritalStatus"
    ],
    drop_first=True
)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 45 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   Attrition                          1470 non-null   int64
 2   DailyRate                          1470 non-null   int64
 3   DistanceFromHome                   1470 non-null   int64
 4   Education                          1470 non-null   int64
 5   EnvironmentSatisfaction            1470 non-null   int64
 6   Gender                             1470 non-null   int32
 7   HourlyRate                         1470 non-null   int64
 8   JobInvolvement                     1470 non-null   int64
 9   JobLevel                           1470 non-null   int64
 10  JobSatisfaction                    1470 non-null   int64
 11  MonthlyIncome                      1470 non-null   int64
 12  MonthlyRate                        1470 non-null   int64
 13  NumCompaniesWorked                 1470 non-null   int64
 14  OverTime                           1470 non-null   int32
 15  PercentSalaryHike                  1470 non-null   int64
 16  PerformanceRating                  1470 non-null   int64
 17  RelationshipSatisfaction           1470 non-null   int64
 18  StockOptionLevel                   1470 non-null   int64
 19  TotalWorkingYears                  1470 non-null   int64
 20  TrainingTimesLastYear              1470 non-null   int64
 21  WorkLifeBalance                    1470 non-null   int64
 22  YearsAtCompany                     1470 non-null   int64
 23  YearsInCurrentRole                 1470 non-null   int64
 24  YearsSinceLastPromotion            1470 non-null   int64
 25  YearsWithCurrManager               1470 non-null   int64
 26  BusinessTravel_Travel_Frequently   1470 non-null   bool
 27  BusinessTravel_Travel_Rarely       1470 non-null   bool
 28  Department_Research & Development  1470 non-null   bool
 29  Department_Sales                   1470 non-null   bool
 30  EducationField_Life Sciences       1470 non-null   bool
 31  EducationField_Marketing           1470 non-null   bool
 32  EducationField_Medical             1470 non-null   bool
 33  EducationField_Other               1470 non-null   bool
 34  EducationField_Technical Degree    1470 non-null   bool
 35  JobRole_Human Resources            1470 non-null   bool
 36  JobRole_Laboratory Technician      1470 non-null   bool
 37  JobRole_Manager                    1470 non-null   bool
 38  JobRole_Manufacturing Director     1470 non-null   bool
 39  JobRole_Research Director          1470 non-null   bool
 40  JobRole_Research Scientist         1470 non-null   bool
 41  JobRole_Sales Executive            1470 non-null   bool
 42  JobRole_Sales Representative       1470 non-null   bool
 43  MaritalStatus_Married              1470 non-null   bool
 44  MaritalStatus_Single               1470 non-null   bool
dtypes: bool(19), int32(2), int64(24)
memory usage: 314.5 KB

In [96]:
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

In [98]:
from sklearn.model_selection import train_test_split

In [100]:
# building the model
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

In [102]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [104]:
print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

(1176, 44)
(294, 44)
Attrition
0    986
1    190
Name: count, dtype: int64
Attrition
0    247
1     47
Name: count, dtype: int64

In [106]:
# standardizing
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [108]:
X_train_scaled = scaler.fit_transform(X_train)

In [110]:
X_test_scaled = scaler.transform(X_test)

In [112]:
# Train the Model
from sklearn.linear_model import LogisticRegression

In [114]:
model = LogisticRegression(random_state=42)

In [116]:
model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [118]:
y_pred = model.predict(X_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [120]:
y_prob = model.predict_proba(X_test_scaled)
y_prob

array([[9.26061582e-01, 7.39384179e-02],
       [9.97681723e-01, 2.31827732e-03],
       [8.90692754e-01, 1.09307246e-01],
       [9.93724418e-01, 6.27558183e-03],
       [6.73490243e-01, 3.26509757e-01],
       [7.23784984e-01, 2.76215016e-01],
       [9.92198352e-01, 7.80164803e-03],
       [9.76638542e-01, 2.33614580e-02],
       [9.96890572e-01, 3.10942815e-03],
       [9.15548441e-01, 8.44515595e-02],
       [9.51088521e-01, 4.89114794e-02],
       [9.16077618e-01, 8.39223821e-02],
       [5.90046387e-01, 4.09953613e-01],
       [8.32636437e-01, 1.67363563e-01],
       [7.14241916e-01, 2.85758084e-01],
       [5.91055640e-01, 4.08944360e-01],
       [9.83694415e-01, 1.63055847e-02],
       [9.94685854e-01, 5.31414595e-03],
       [7.32588149e-01, 2.67411851e-01],
       [9.88372709e-01, 1.16272906e-02],
       [5.33346186e-01, 4.66653814e-01],
       [8.96281802e-01, 1.03718198e-01],
       [8.89228020e-01, 1.10771980e-01],
       [9.87131598e-01, 1.28684018e-02],
       [9.95774007e-01, 4.22599325e-03],
       [4.87654674e-01, 5.12345326e-01],
       [9.12820835e-01, 8.71791650e-02],
       [9.28304023e-01, 7.16959770e-02],
       [9.91960220e-01, 8.03977992e-03],
       [9.91343164e-01, 8.65683591e-03],
       [9.93947751e-01, 6.05224909e-03],
       [8.49714690e-01, 1.50285310e-01],
       [9.48169650e-01, 5.18303495e-02],
       [9.31166265e-01, 6.88337355e-02],
       [8.21670959e-01, 1.78329041e-01],
       [1.79583445e-01, 8.20416555e-01],
       [9.84894327e-01, 1.51056733e-02],
       [9.76866767e-01, 2.31332332e-02],
       [9.46530489e-01, 5.34695114e-02],
       [5.01148039e-01, 4.98851961e-01],
       [9.96824137e-01, 3.17586293e-03],
       [4.33157677e-01, 5.66842323e-01],
       [9.89575185e-01, 1.04248145e-02],
       [9.58859655e-01, 4.11403447e-02],
       [8.85682979e-01, 1.14317021e-01],
       [9.48689339e-01, 5.13106609e-02],
       [6.07296722e-01, 3.92703278e-01],
       [6.12757434e-01, 3.87242566e-01],
       [9.78193558e-01, 2.18064419e-02],
       [9.43905979e-01, 5.60940209e-02],
       [9.15840410e-01, 8.41595900e-02],
       [9.74356325e-01, 2.56436751e-02],
       [9.84815331e-01, 1.51846687e-02],
       [7.61628892e-01, 2.38371108e-01],
       [9.85274860e-01, 1.47251398e-02],
       [9.72210638e-01, 2.77893622e-02],
       [9.64732958e-01, 3.52670416e-02],
       [2.02896441e-01, 7.97103559e-01],
       [9.18794814e-01, 8.12051859e-02],
       [9.81477126e-01, 1.85228738e-02],
       [9.62015980e-01, 3.79840196e-02],
       [9.96976237e-01, 3.02376258e-03],
       [9.82719704e-01, 1.72802958e-02],
       [9.15664826e-01, 8.43351742e-02],
       [9.09669370e-01, 9.03306299e-02],
       [9.79798011e-01, 2.02019895e-02],
       [8.47284938e-01, 1.52715062e-01],
       [7.48934443e-01, 2.51065557e-01],
       [9.17646097e-01, 8.23539029e-02],
       [9.71991441e-01, 2.80085592e-02],
       [5.69346522e-01, 4.30653478e-01],
       [9.95327695e-01, 4.67230504e-03],
       [9.95865876e-01, 4.13412426e-03],
       [9.18209207e-01, 8.17907932e-02],
       [9.54947937e-01, 4.50520625e-02],
       [9.93260214e-01, 6.73978610e-03],
       [9.99431789e-01, 5.68210514e-04],
       [9.92107016e-01, 7.89298442e-03],
       [8.31120108e-01, 1.68879892e-01],
       [9.84127407e-01, 1.58725934e-02],
       [9.77156091e-01, 2.28439085e-02],
       [1.40881981e-01, 8.59118019e-01],
       [9.96984854e-01, 3.01514599e-03],
       [9.99393028e-01, 6.06972374e-04],
       [9.70231562e-01, 2.97684384e-02],
       [8.81388705e-01, 1.18611295e-01],
       [9.97580570e-01, 2.41943039e-03],
       [8.98586669e-01, 1.01413331e-01],
       [9.73017728e-01, 2.69822723e-02],
       [9.39322541e-01, 6.06774589e-02],
       [9.77135252e-01, 2.28647476e-02],
       [9.97058524e-01, 2.94147606e-03],
       [2.91454141e-02, 9.70854586e-01],
       [7.57215783e-01, 2.42784217e-01],
       [7.57524600e-01, 2.42475400e-01],
       [1.28168121e-01, 8.71831879e-01],
       [3.51492418e-01, 6.48507582e-01],
       [9.52271054e-01, 4.77289459e-02],
       [8.59203603e-01, 1.40796397e-01],
       [5.68691668e-01, 4.31308332e-01],
       [9.98957594e-01, 1.04240591e-03],
       [3.58747137e-01, 6.41252863e-01],
       [8.80153483e-01, 1.19846517e-01],
       [9.80039688e-01, 1.99603119e-02],
       [3.50834948e-01, 6.49165052e-01],
       [9.74695055e-01, 2.53049448e-02],
       [9.25160308e-01, 7.48396923e-02],
       [9.99704461e-01, 2.95539059e-04],
       [8.82811141e-01, 1.17188859e-01],
       [9.14070941e-01, 8.59290592e-02],
       [7.09543366e-01, 2.90456634e-01],
       [8.49807602e-01, 1.50192398e-01],
       [9.74304760e-01, 2.56952403e-02],
       [8.94658841e-01, 1.05341159e-01],
       [9.29941391e-01, 7.00586088e-02],
       [9.56533156e-01, 4.34668439e-02],
       [9.37105919e-01, 6.28940806e-02],
       [9.67304372e-01, 3.26956283e-02],
       [9.52757145e-01, 4.72428548e-02],
       [9.83243586e-01, 1.67564141e-02],
       [9.26386616e-01, 7.36133840e-02],
       [6.34786405e-01, 3.65213595e-01],
       [9.92589211e-01, 7.41078879e-03],
       [8.79559256e-01, 1.20440744e-01],
       [3.40775969e-01, 6.59224031e-01],
       [9.70512692e-01, 2.94873075e-02],
       [6.45596209e-01, 3.54403791e-01],
       [3.73750733e-01, 6.26249267e-01],
       [8.37530189e-01, 1.62469811e-01],
       [9.25006687e-01, 7.49933126e-02],
       [2.96287127e-01, 7.03712873e-01],
       [9.96788295e-01, 3.21170541e-03],
       [9.55697895e-01, 4.43021048e-02],
       [5.78148118e-01, 4.21851882e-01],
       [9.30410572e-01, 6.95894283e-02],
       [8.94265543e-01, 1.05734457e-01],
       [6.08976484e-01, 3.91023516e-01],
       [8.45682101e-01, 1.54317899e-01],
       [8.25343670e-01, 1.74656330e-01],
       [9.95572811e-01, 4.42718938e-03],
       [9.99338653e-01, 6.61347027e-04],
       [9.94052794e-01, 5.94720575e-03],
       [9.47279131e-01, 5.27208689e-02],
       [3.31742035e-01, 6.68257965e-01],
       [7.53236128e-01, 2.46763872e-01],
       [9.81389377e-01, 1.86106231e-02],
       [7.08191233e-01, 2.91808767e-01],
       [9.36809237e-01, 6.31907633e-02],
       [9.82591141e-01, 1.74088588e-02],
       [9.97941037e-01, 2.05896260e-03],
       [9.83836558e-01, 1.61634418e-02],
       [9.17854675e-01, 8.21453249e-02],
       [9.23506162e-01, 7.64938379e-02],
       [9.95443336e-01, 4.55666382e-03],
       [9.62514194e-01, 3.74858062e-02],
       [7.02208896e-01, 2.97791104e-01],
       [7.86043829e-01, 2.13956171e-01],
       [9.96184719e-01, 3.81528140e-03],
       [2.69129873e-01, 7.30870127e-01],
       [8.00883212e-01, 1.99116788e-01],
       [9.44706521e-01, 5.52934793e-02],
       [9.49031468e-01, 5.09685318e-02],
       [8.94096157e-01, 1.05903843e-01],
       [9.86727471e-01, 1.32725294e-02],
       [6.99136549e-01, 3.00863451e-01],
       [9.77974870e-01, 2.20251301e-02],
       [9.49454317e-01, 5.05456826e-02],
       [8.59764139e-01, 1.40235861e-01],
       [5.67209461e-01, 4.32790539e-01],
       [9.55752754e-01, 4.42472460e-02],
       [7.83953231e-01, 2.16046769e-01],
       [9.60617805e-01, 3.93821953e-02],
       [5.14346824e-01, 4.85653176e-01],
       [4.90145577e-01, 5.09854423e-01],
       [8.22904125e-01, 1.77095875e-01],
       [9.90818260e-01, 9.18174043e-03],
       [4.96072931e-01, 5.03927069e-01],
       [9.96186285e-01, 3.81371468e-03],
       [8.52808125e-01, 1.47191875e-01],
       [9.06085436e-01, 9.39145640e-02],
       [7.61003034e-01, 2.38996966e-01],
       [8.77262260e-01, 1.22737740e-01],
       [9.66911261e-01, 3.30887392e-02],
       [5.80289436e-01, 4.19710564e-01],
       [9.69072369e-01, 3.09276309e-02],
       [9.96901216e-01, 3.09878414e-03],
       [9.85870914e-01, 1.41290864e-02],
       [9.91461062e-01, 8.53893841e-03],
       [9.85348218e-01, 1.46517825e-02],
       [6.10423785e-01, 3.89576215e-01],
       [7.85313268e-01, 2.14686732e-01],
       [9.80160660e-01, 1.98393404e-02],
       [9.31139540e-01, 6.88604602e-02],
       [9.91747551e-01, 8.25244864e-03],
       [9.99679473e-01, 3.20526766e-04],
       [7.63237573e-01, 2.36762427e-01],
       [8.99015915e-01, 1.00984085e-01],
       [8.40966087e-01, 1.59033913e-01],
       [9.43939761e-01, 5.60602391e-02],
       [8.52615660e-01, 1.47384340e-01],
       [1.26310668e-01, 8.73689332e-01],
       [9.96682803e-01, 3.31719665e-03],
       [9.50397582e-01, 4.96024177e-02],
       [8.41986594e-01, 1.58013406e-01],
       [8.75474987e-01, 1.24525013e-01],
       [9.98996148e-01, 1.00385165e-03],
       [9.91905229e-01, 8.09477124e-03],
       [7.71819413e-01, 2.28180587e-01],
       [9.64676870e-01, 3.53231304e-02],
       [9.84596747e-01, 1.54032535e-02],
       [9.59494285e-01, 4.05057150e-02],
       [9.94568693e-01, 5.43130674e-03],
       [9.97334339e-01, 2.66566082e-03],
       [9.39521803e-01, 6.04781968e-02],
       [2.00905523e-02, 9.79909448e-01],
       [9.24805864e-01, 7.51941364e-02],
       [9.83307220e-01, 1.66927795e-02],
       [9.42220654e-01, 5.77793464e-02],
       [8.99638623e-01, 1.00361377e-01],
       [3.78316039e-01, 6.21683961e-01],
       [9.98248224e-01, 1.75177601e-03],
       [9.44992234e-01, 5.50077656e-02],
       [8.07480496e-01, 1.92519504e-01],
       [4.44298939e-01, 5.55701061e-01],
       [7.63179559e-01, 2.36820441e-01],
       [9.78871859e-01, 2.11281414e-02],
       [8.95353423e-01, 1.04646577e-01],
       [6.68874805e-01, 3.31125195e-01],
       [9.97949571e-01, 2.05042915e-03],
       [9.77645647e-01, 2.23543534e-02],
       [9.74212133e-01, 2.57878672e-02],
       [9.88274477e-01, 1.17255232e-02],
       [9.71531332e-01, 2.84686676e-02],
       [9.74286796e-01, 2.57132040e-02],
       [9.98466299e-01, 1.53370067e-03],
       [8.51529166e-01, 1.48470834e-01],
       [9.70488876e-01, 2.95111242e-02],
       [9.85439671e-01, 1.45603290e-02],
       [9.59708122e-01, 4.02918779e-02],
       [9.40092069e-01, 5.99079305e-02],
       [9.99367736e-01, 6.32264169e-04],
       [7.69140720e-01, 2.30859280e-01],
       [9.96093295e-01, 3.90670533e-03],
       [8.13625397e-01, 1.86374603e-01],
       [9.71775732e-01, 2.82242680e-02],
       [7.42303043e-01, 2.57696957e-01],
       [9.62985603e-01, 3.70143973e-02],
       [9.41427806e-01, 5.85721935e-02],
       [9.53802002e-01, 4.61979981e-02],
       [9.63167322e-01, 3.68326776e-02],
       [3.66285822e-01, 6.33714178e-01],
       [6.79477445e-01, 3.20522555e-01],
       [9.76178997e-01, 2.38210026e-02],
       [8.89341835e-01, 1.10658165e-01],
       [9.97591733e-01, 2.40826733e-03],
       [9.88512042e-01, 1.14879583e-02],
       [1.81779979e-01, 8.18220021e-01],
       [8.65997588e-01, 1.34002412e-01],
       [9.40467219e-01, 5.95327808e-02],
       [9.97159621e-01, 2.84037913e-03],
       [9.99669087e-01, 3.30913295e-04],
       [9.92252681e-01, 7.74731895e-03],
       [9.97861551e-01, 2.13844881e-03],
       [9.96129171e-01, 3.87082857e-03],
       [9.88696686e-01, 1.13033136e-02],
       [9.13846783e-01, 8.61532167e-02],
       [9.68738781e-01, 3.12612190e-02],
       [9.25876050e-01, 7.41239499e-02],
       [9.62133776e-01, 3.78662243e-02],
       [9.98011144e-01, 1.98885601e-03],
       [7.08227175e-01, 2.91772825e-01],
       [9.83618104e-01, 1.63818955e-02],
       [9.69495472e-01, 3.05045282e-02],
       [3.69739155e-01, 6.30260845e-01],
       [9.94910522e-01, 5.08947843e-03],
       [8.51183126e-01, 1.48816874e-01],
       [3.81340734e-01, 6.18659266e-01],
       [9.13230736e-01, 8.67692637e-02],
       [9.05245914e-01, 9.47540858e-02],
       [8.11469870e-01, 1.88530130e-01],
       [9.50927180e-01, 4.90728200e-02],
       [8.74572010e-01, 1.25427990e-01],
       [9.39946193e-01, 6.00538067e-02],
       [8.21127079e-01, 1.78872921e-01],
       [9.68781766e-01, 3.12182343e-02],
       [8.12999225e-01, 1.87000775e-01],
       [9.99078386e-01, 9.21614053e-04],
       [2.23496427e-01, 7.76503573e-01],
       [7.65426046e-01, 2.34573954e-01],
       [9.86887155e-01, 1.31128450e-02],
       [9.91638535e-01, 8.36146533e-03],
       [5.28822695e-01, 4.71177305e-01],
       [9.91905278e-01, 8.09472176e-03],
       [9.97823044e-01, 2.17695585e-03]])

In [122]:
# Evaluate the Model
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

In [124]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob[:,1]))

Accuracy : 0.8605442176870748
Precision: 0.6153846153846154
Recall   : 0.3404255319148936
F1 Score : 0.4383561643835616
ROC-AUC  : 0.8079076578516668

In [126]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[237  10]
 [ 31  16]]

In [128]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [130]:
y_pred_dt = dt_model.predict(X_test)

y_prob_dt = dt_model.predict_proba(X_test)

In [132]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_dt[:,1]))

Accuracy : 0.7585034013605442
Precision: 0.29310344827586204
Recall   : 0.3617021276595745
F1 Score : 0.3238095238095238
ROC-AUC  : 0.5978551124127831

In [134]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_dt))

[[206  41]
 [ 30  17]]

In [136]:
# Random Forest 
from sklearn.ensemble import RandomForestClassifier

In [138]:
rf_model = RandomForestClassifier(
    random_state=42
)

In [140]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [142]:
# PREDICTIONS 
y_pred_rf = rf_model.predict(X_test)

y_prob_rf = rf_model.predict_proba(X_test)

In [144]:
# evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_rf[:,1]))

Accuracy : 0.826530612244898
Precision: 0.3
Recall   : 0.06382978723404255
F1 Score : 0.10526315789473684
ROC-AUC  : 0.7864157119476268

In [146]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_rf))

[[240   7]
 [ 44   3]]

In [150]:
# XGBOOST
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\janud\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\janud\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
    --------------------------------------- 1.3/69.5 MB 6.7 MB/s eta 0:00:11
   - -------------------------------------- 3.1/69.5 MB 8.0 MB/s eta 0:00:09
   --- ------------------------------------ 5.2/69.5 MB 8.6 MB/s eta 0:00:08
   ---- ----------------------------------- 7.1/69.5 MB 8.7 MB/s eta 0:00:08
   ----- ---------------------------------- 9.2/69.5 MB 8.8 MB/s eta 0:00:07
   ------ --------------------------------- 11.0/69.5 MB 8.9 MB/s eta 0:00:07
   ------- -------------------------------- 12.6/69.5 MB 8.7 MB/s eta 0:00:07
   -------- ------------------------------- 14.9/69.5 MB 9.0 MB/s eta 0:00:07
   --------- ------------------------------ 17.3/69.5 MB 9.1 MB/s eta 0:00:06
   ----------- ---------------------------- 19.4/69.5 MB 9.2 MB/s eta 0:00:06
   ------------ --------------------------- 21.8/69.5 MB 9.4 MB/s eta 0:00:06
   ------------- -------------------------- 24.1/69.5 MB 9.5 MB/s eta 0:00:05
   -------------- ------------------------- 25.4/69.5 MB 9.3 MB/s eta 0:00:05
   --------------- ------------------------ 27.3/69.5 MB 9.2 MB/s eta 0:00:05
   ---------------- ----------------------- 28.8/69.5 MB 9.1 MB/s eta 0:00:05
   ------------------ --------------------- 31.5/69.5 MB 9.2 MB/s eta 0:00:05
   ------------------- -------------------- 33.3/69.5 MB 9.2 MB/s eta 0:00:04
   -------------------- ------------------- 35.4/69.5 MB 9.2 MB/s eta 0:00:04
   --------------------- ------------------ 36.7/69.5 MB 9.0 MB/s eta 0:00:04
   --------------------- ------------------ 38.0/69.5 MB 8.9 MB/s eta 0:00:04
   ----------------------- ---------------- 40.4/69.5 MB 9.0 MB/s eta 0:00:04
   ------------------------ --------------- 42.5/69.5 MB 9.1 MB/s eta 0:00:03
   ------------------------- -------------- 44.6/69.5 MB 9.1 MB/s eta 0:00:03
   -------------------------- ------------- 46.7/69.5 MB 9.1 MB/s eta 0:00:03
   --------------------------- ------------ 48.5/69.5 MB 9.1 MB/s eta 0:00:03
   ---------------------------- ----------- 50.3/69.5 MB 9.1 MB/s eta 0:00:03
   ------------------------------ --------- 52.4/69.5 MB 9.0 MB/s eta 0:00:02
   ------------------------------- -------- 54.5/69.5 MB 9.1 MB/s eta 0:00:02
   ------------------------------- -------- 55.1/69.5 MB 9.1 MB/s eta 0:00:02
   -------------------------------- ------- 56.1/69.5 MB 8.8 MB/s eta 0:00:02
   -------------------------------- ------- 57.1/69.5 MB 8.6 MB/s eta 0:00:02
   --------------------------------- ------ 59.0/69.5 MB 8.6 MB/s eta 0:00:02
   ----------------------------------- ---- 61.1/69.5 MB 8.6 MB/s eta 0:00:01
   ------------------------------------ --- 63.4/69.5 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 65.3/69.5 MB 8.7 MB/s eta 0:00:01
   -------------------------------------- - 67.1/69.5 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  68.7/69.5 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 8.4 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

In [152]:
from xgboost import XGBClassifier

In [154]:
# build the model
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [156]:
# train
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [158]:
# Predictions
y_pred_xgb = xgb_model.predict(X_test)

y_prob_xgb = xgb_model.predict_proba(X_test)

In [160]:
# evaluation
print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall   :", recall_score(y_test, y_pred_xgb))
print("F1 Score :", f1_score(y_test, y_pred_xgb))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_xgb[:,1]))

Accuracy : 0.8605442176870748
Precision: 0.65
Recall   : 0.2765957446808511
F1 Score : 0.3880597014925373
ROC-AUC  : 0.7638039452149195